blank_issues_enabled: false # must use template
contact_links:
  - name: ColorMaster Community Support
    url: https://github.com/lbragile/ColorMaster/discussions
    about: Please ask and answer questions here.
