name: CodeQL Security Inspection

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]
  schedule:
    - cron: "39 19 * * 3,6"

jobs:
  code-security:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: "javascript"

      - name: Perform Analysis
        uses: github/codeql-action/analyze@v1
