name: Documentation

on:
  push:
    branches: ["develop"]

jobs:
  docs:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Documentation
        run: npm run deploy

      - name: Provide Link
        run: echo "Documentation is available at https://lbragile.github.io/ColorMaster/"
